---
# tasks file for miglesias.bastion-tasks
- name: Step 1 - Bastion Tasks
  debug: msg="Environment GUID={{guid}}"
- name: 1.1 Create workdir Folder (if it does not exist)
  file: 
    path: "{{ ANSIBLE_REPO_PATH }}/workdir"
    mode: 0755 
    state: directory
- name: 1.2 Generate Ansible Hosts File
  template:
    src: "hosts_template.j2"
    dest: "{{ ANSIBLE_REPO_PATH }}/workdir/hosts-{{ guid }}"
- name: 1.3 Overwrite Ansible Hosts File
  copy:
    src: "{{ ANSIBLE_REPO_PATH }}/workdir/hosts-{{ guid }}"
    dest: /etc/ansible/hosts
