---
- name: Step 1 - OpenShift Provisioning
  ping:
- name: Step 2 - Prepare GUID environment variable across all hosts
  shell: export GUID=`hostname | cut -d"." -f2`; echo "export GUID=$GUID" >> $HOME/.bashrc

